const psetSlugs = ["osn-2022", "ksn-2021", "ksn-2020", "osn-2019", "osn-2018"];

const usernames = [
  "Ackhava",
  "akram1717",
  "bagasangga",
  "palpale",
  "Ryan_Ethan_Halim",
  "cly0402",
  "faeilana",
  "kayna",
  "worthytacos",
  "Sentreb",
  "glenaoi",
  "trianandaharahap",
  "MikiMiku",
  "MuhammadFakhryZaki",
  "Mitty_123",
  "Jesslyn_nathania19",
  "harzuqi",
  "davinpwk",
  "matthewhutama",
  "Sokuzo21",
  "eur",
  "Michael_H",
  "Raoul",
  "lalaiing",
  "syfa",
  "dhapin",
  "Rayhanrizqy",
  "Fon1as",
  "vinren",
  "Yazid_H",
  "habib_rizqi",
  "adamnooriman",
  "DhimasPutra ",
  "felejunelus",
  "bananade",
  "HannanAfif",
  "AdrielJ",
  "Miko",
  "IDika",
  "MoonLord",
  "O_O",
  "Lenvil",
  "Lucia",
  "Nothing123",
  "Kloce",
];

const usernameToUserDataMap = {
  Ackhava: { name: "Ackhava Adam Malonda", province: "Prov. Bali" },
  akram1717: { name: "Nashiruddin Akram", province: "Prov. Banten" },
  bagasangga: {
    name: "Bagas Anggareksa Irsyad Dhanisywara",
    province: "Prov. D.I. Yogyakarta",
  },
  palpale: { name: "Hanif Achdan Pietoyo", province: "Prov. D.I. Yogyakarta" },
  Ryan_Ethan_Halim: {
    name: "Ryan Ethan Halim",
    province: "Prov. D.I. Yogyakarta",
  },
  cly0402: { name: "Clayton Luther Young", province: "Prov. D.K.I. Jakarta" },
  faeilana: { name: "Fae Ilana Negoro", province: "Prov. D.K.I. Jakarta" },
  kayna: { name: "Kayna Mufidah", province: "Prov. D.K.I. Jakarta" },
  worthytacos: {
    name: "Kevin Cornellius Widjaja",
    province: "Prov. D.K.I. Jakarta",
  },
  Sentreb: {
    name: "Mochammad Fathirrazi Nafisandy",
    province: "Prov. D.K.I. Jakarta",
  },
  glenaoi: {
    name: "Stanislaus Harglen Utama Sitompul",
    province: "Prov. D.K.I. Jakarta",
  },
  trianandaharahap: {
    name: "Triananda Marsya Harahap",
    province: "Prov. Jambi",
  },
  MikiMiku: { name: "Jonathan Irvin Susanto", province: "Prov. Jawa Barat" },
  MuhammadFakhryZaki: {
    name: "Muhammad Fakhry Zaki",
    province: "Prov. Jawa Barat",
  },
  Mitty_123: {
    name: "Muhammad Fatih Irkham Mauludi",
    province: "Prov. Jawa Barat",
  },
  Jesslyn_nathania19: {
    name: "Nathania Jesslyn",
    province: "Prov. Jawa Barat",
  },
  harzuqi: { name: "Azzam Harzuqi", province: "Prov. Jawa Tengah" },
  davinpwk: { name: "Davin Pandya Wala Khotob", province: "Prov. Jawa Tengah" },
  matthewhutama: {
    name: "Matthew Hutama Pramana",
    province: "Prov. Jawa Tengah",
  },
  Sokuzo21: { name: "Muhammad Daffa Daneswara", province: "Prov. Jawa Tengah" },
  eur: { name: "Annabel Kayla Talitha", province: "Prov. Jawa Timur" },
  Michael_H: { name: "Michael Hartono", province: "Prov. Jawa Timur" },
  Raoul: { name: "Raoul Corrinthian", province: "Prov. Jawa Timur" },
  lalaiing: { name: "Stella Ling Raharjo", province: "Prov. Jawa Timur" },
  syfa: { name: "Syauqi Faza", province: "Prov. Jawa Timur" },
  dhapin: {
    name: "Muhammad Dhafin Al Khairy",
    province: "Prov. Kalimantan Timur",
  },
  Rayhanrizqy: {
    name: "Rayhan Rizky Ramadhan",
    province: "Prov. Kalimantan Utara",
  },
  Fon1as: { name: "Fatih Naufal Habibillah", province: "Prov. Lampung" },
  vinren: { name: "Vincent Valentino Oei", province: "Prov. Maluku" },
  Yazid_H: {
    name: "Yazid Aqila Haikal",
    province: "Prov. Nusa Tenggara Barat",
  },
  habib_rizqi: {
    name: "Habib Firjatulah Rizqi",
    province: "Prov. Papua Barat",
  },
  adamnooriman: { name: "Adam Nooriman", province: "Prov. Papua Selatan" },
  DhimasPutra: { name: "Dhimas Putra Sulistio", province: "Prov. Riau" },
  felejunelus: { name: "Felesia Junelus", province: "Prov. Riau" },
  bananade: { name: "Franklin Filbert Irwan", province: "Prov. Riau" },
  HannanAfif: { name: "Hannan Afif Darmawan", province: "Prov. Riau" },
  AdrielJ: {
    name: "Adriel Jansen Siahaya",
    province: "Prov. Sulawesi Selatan",
  },
  Miko: { name: "Michael Widjaja", province: "Prov. Sulawesi Selatan" },
  IDika: {
    name: "Andika Pratama Putra Nugraha",
    province: "Prov. Sulawesi Utara",
  },
  MoonLord: { name: "Ahmad Fauzan Putra", province: "Prov. Sumatera Barat" },
  O_O: { name: "Bermulya Anugrah Putra", province: "Prov. Sumatera Barat" },
  Lenvil: { name: "Leroy Ben Orvill", province: "Prov. Sumatera Selatan" },
  Lucia: { name: "Lucia Giovani", province: "Prov. Sumatera Selatan" },
  Nothing123: {
    name: "Vergeo Valentino Gunawan",
    province: "Prov. Sumatera Selatan",
  },
  Kloce: {
    name: "Kloce Paul William Saragih",
    province: "Prov. Sumatera Utara",
  },
};

export { usernames, usernameToUserDataMap, psetSlugs };
